New build and run system

diff --git a/kernel/get-deps b/kernel/get-deps
--- a/kernel/get-deps
+++ b/kernel/get-deps
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-set -ex
+set -e
 
 srcdir="$(dirname "$0")"
 test -z "$srcdir" && srcdir=.
@@ -11,70 +11,41 @@ clone_repo_commit() {
     if test -d "$2/.git"; then
         git -C "$2" reset --hard
         git -C "$2" clean -fd
-        if ! git -C "$2" checkout $3; then
+        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
             rm -rf "$2"
         fi
     else
         if test -d "$2"; then
-            set +x
-            echo "error: '$2' is not a Git repository"
+            echo "error: '$2' is not a Git repository" 1>&2
             exit 1
         fi
     fi
     if ! test -d "$2"; then
         git clone $1 "$2"
-        if ! git -C "$2" checkout $3; then
+        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
             rm -rf "$2"
             exit 1
         fi
     fi
 }
 
-download_by_hash() {
-    DOWNLOAD_COMMAND="curl -Lo"
-    if ! command -v $DOWNLOAD_COMMAND >/dev/null 2>&1; then
-        DOWNLOAD_COMMAND="wget -O"
-        if ! command -v $DOWNLOAD_COMMAND >/dev/null 2>&1; then
-            set +x
-            echo "error: Neither curl nor wget found"
-            exit 1
-        fi
-    fi
-    SHA256_COMMAND="sha256sum"
-    if ! command -v $SHA256_COMMAND >/dev/null 2>&1; then
-        SHA256_COMMAND="sha256"
-        if ! command -v $SHA256_COMMAND >/dev/null 2>&1; then
-            set +x
-            echo "error: Cannot find sha256(sum) command"
-            exit 1
-        fi
-    fi
-    if ! test -f "$2" || ! $SHA256_COMMAND "$2" | grep $3 >/dev/null 2>&1; then
-        rm -f "$2"
-        mkdir -p "$2" && rm -rf "$2"
-        $DOWNLOAD_COMMAND "$2" $1
-        if ! $SHA256_COMMAND "$2" | grep $3 >/dev/null 2>&1; then
-            set +x
-            echo "error: Cannot download file '$2' by hash"
-            echo "incorrect hash:"
-            $SHA256_COMMAND "$2"
-            rm -f "$2"
-            exit 1
-        fi
-    fi
-}
+rm -f .deps-obtained
 
 clone_repo_commit \
-    https://github.com/osdev0/freestnd-c-hdrs-0bsd.git \
-    freestnd-c-hdrs-0bsd \
-    a87c192f3eb66b0806740dc67325f9ad23fc2d0b
+    https://codeberg.org/OSDev/freestnd-c-hdrs-0bsd.git \
+    freestnd-c-hdrs \
+    5e4e9e70278fe89ea328d359a58aff4f4a94b165
 
 clone_repo_commit \
-    https://github.com/osdev0/cc-runtime.git \
+    https://codeberg.org/OSDev/cc-runtime.git \
     cc-runtime \
-    576a01179f3298a4795b92f42c088f9f8800b56b
+    dae79833b57a01b9fd3e359ee31def69f5ae899b
 
-download_by_hash \
-    https://github.com/limine-bootloader/limine/raw/e7a0cedca2369a32c8dde69d99f0648b6961ece7/limine.h \
-    src/limine.h \
-    f8b35287579dbe50e9d84cca7b558e39b2b64e499f9b37ef5ebe969c05104c33
+clone_repo_commit \
+    https://codeberg.org/Limine/limine-protocol.git \
+    limine-protocol \
+    fedf97facd1c473ee8720f8dfd5a71d03490d928
+
+touch .deps-obtained
+
+printf "\nDependencies obtained successfully.\n"
